### ISSUE TITLE
Codegen is broken for `optional` fields

### ISSUE THREAD

**Issue by nick-kentik** [joeycumines/protoc-gen-go-copy#2]
From v3.12, `protoc` has had support for the `optional` keyword. It was experimental (off by default) until 3.15, when it became enabled by default: https://github.com/protocolbuffers/protobuf/blob/v3.19.0/docs/field_presence.md#how-to-enable-explicit-presence-in-proto3

I've got a message in a proto3 proto that I added this to:

```proto
message Foo {
  // ...
  optional int64 bar = 3; 
}
```

The generated `.pb.go` makes a struct for the message with:

```go
type Foo struct {
    // ...
    Bar *int64 `protobuf:"varint,3,opt,name=bar,json=bar,proto3,oneof" json:"bar,omitempty"`
}
```

The generated `_copy.pb.go` makes:

```go
func (x *Foo) Proto_ShallowCopy(v interface{}) {
	switch v := v.(type) {
	case *Foo:
                // ...
		x.XBar = v.GetXBar()
	default:
                // ...
		if v, ok := v.(interface {
			GetXBar() isFoo_XBar
		}); ok {
			x.XBar = v.GetXBar()
		} else {
			func() {
				if v, ok := v.(interface{ GetBar() int64 }); ok {
					var defaultValue int64
					if v := v.GetBar(); v != defaultValue {
						x.XBar = &Foo_Bar{Bar: v}
						return
					}
				}
			}()
		}
	}
}

// Proto_ShallowClone returns a shallow copy of the receiver or nil if it's nil.
func (x *Foo) Proto_ShallowClone() (c *Foo) {
	if x != nil {
		c = new(Foo)
		// ...
		c.XBar = x.XBar
	}
	return
}
```

The issues I noticed:

* The field gets named `XBar` instead of `Bar`
* The getts get named `GetXBar()` instead of `GetBar()`
* References unknown type `isFoo_XBar`
* References unknown type `Foo_Bar`

I'm very early in investigating this, and TBH might decide that it's too much work to try to fix :sweat_smile: - I could always use implicit presence instead, after all. Thought I'd capture the issue at least, though.

**Comment by joeycumines** [comment]
Thanks for this @nick-kentik.

The fact the use of `optional` is no longer experimental makes me want to address it, but I'm not certain how best to handle such fields.

I'd lean towards just treating them in a very similar (basic) manner, and:

- Not copying the values (e.g. just setting `Foo.Bar` to the same pointer, in your example)
- Continuing to avoid switching behavior on field presence (i.e. for copy - in contrast to [proto.Merge](https://pkg.go.dev/github.com/golang/protobuf/proto#Merge))

Thoughts?

**Comment by nick-kentik** [comment]
Hey,

Basic treatment would be fine for me - in the end it's just another shallow copy, after all.

For my own project I've dropped the `optional` specifier for now, but it would be lovely to be able to use it in the future.

**Comment by joeycumines** [comment]
Should be fixed now @nick-kentik.

Minor caveat that you likely won't care about: copy can't work for optional fields if source type isn't the same as the destination type, as the getters for most of protobuf's scalar types don't return a type that supports presence, even with optional set.

**Comment by nick-kentik** [comment]
Amazing, thanks!
